version: 0.0
os: linux

files:
  - source: files/
    destination: /var/www/html


hooks:
  BeforeInstall:
    - location: scripts/deregister_from_elb.sh
    - location: scripts/webserver-stop.sh
  AfterInstall:
    - location: scripts/sleep.sh
    - location: scripts/webserver-start.sh
    - location:	scripts/register_with_elb.sh
